# Generated by Django 6.0.6 on 2026-06-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='phone_no',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='service_of_intrest',
        ),
    ]
